### ISSUE TITLE
build problem in mac

### ISSUE THREAD

**Issue by Biisairo** [durken1/pierce#9]
I'm almost done with my project and have a question.
I have two issues.
First. When I power on and connect, the left side connects immediately, while the right side either doesn't connect or takes a long time to connect.
Second. When the distance from the transmitter is more than 5cm, it doesn't connect properly.

Additionally, I don't have a Windows PC, so I used brew on my Mac to install openocd and stlink.

**Comment by durken1** [comment]
Not sure what could cause those problems to be honest, I haven't had any issues like that in any of my builds. I have tested the connection up to about 5 m away and through a door without problems.

There is an option to define what channels to use for the wireless connection, and using interleaved channels for the left and right modules should improve stability in theory, but I never got around to implementing it since it worked fine for me, but that might be something worth checking out. Just let me know if you need any help with that.

Faulty hardware is of course also possible, do you have additional modules you could try?

**Comment by Biisairo** [comment]
I apologize for not replying for so long. 

I tried creating a new receiver, but the situation is the same.
If it's a problem with the transmitter (keyboard), I can't create one right now, so I'm not sure yet.
My friend who is building it with me says he's still working on it, so I'll wait and see.

Additionally, 
Have you tried flashing the firmware using macos?
I used brew to install openocd and telnet and then flashed it.
I'm not sure if it's my device or the flash process that's the problem.
If you have a macos machine, could you please test the firmware flash with macos?

**Comment by Biisairo** [comment]
Hold on a second
Looking at the PCB, it looks like there is no ground under the antenna part of the wireless module.
If there is a ground under the antenna, will this cause a weak signal and prevent it from connecting properly?

The reason I ask this question is because I made a little modification to the PCB

**Comment by durken1** [comment]
Yes, a ground plane under the antenna would weaken the signal.

Regarding macOS I dont have access to a Mac, so I cant test that. 

Have you double checked all the soldier joints for the wireless modules on the keyboard? Preferably with a multimeter to be sure there are no shorts.

**Comment by Biisairo** [comment]
The keyboard I made worked with a very weak signal at very close range.
I think it's probably the ground under the antenna I mentioned above.
My partner says he can fix the board and send it to me in a month or two, so I'll try to build it again and let you know.
Thanks a lot for the reply.

**Comment by durken1** [comment]
Alright. I'll close this issue then.
Let me know if you need anything else!
